[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "multer", "ytdl-core", "fluent-ffmpeg", "@ffmpeg-installer/ffmpeg"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
